#!/usr/bin/env bash

# Update the system and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the hostname of the server
hostname=$(hostname)

# Configure Nginx to add custom header
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo service nginx restart

# Display a message indicating successful configuration
echo "Nginx configured with custom HTTP response header on $hostname"

